Verify suite - default behaviour
bosonprotocol/boson-protocol-contracts pull request #464
Opened 2022-11-09 08:25 UTC by zajck

This PR introduces some changes in verify suite:

- contract list to be verified is supplied in file `scripts/config/contract-verification.js` and not hardcoded in hardhat config
- if contract list is empty it tries to verify everything
- just slightly changed what env represents so it's in line with other scripts
- task.md was updated to mention how to verify only a subset of contracts

2022-11-10 17:08 UTC, hswopeams requested changes

2022-11-10 17:14 UTC, cliffhall requested changes
Just a few typos

2022-11-10 17:14 UTC, cliffhall commented on scripts/config/contract-verification.js
> + * List of contract to verify on explorer, using verify-suite script
~~contract~~  contracts

2022-11-10 17:14 UTC, cliffhall commented on scripts/config/contract-verification.js
> + *  1a. If you want to verify all contract, leave contractList empty
~~contract~~  contracts

2022-11-10 17:14 UTC, cliffhall commented on scripts/config/contract-verification.js
> + *  1b. If you want to verify only a subset of contract, specify them in contractList.
~~contract~~  contracts

2022-11-10 17:14 UTC, cliffhall commented on scripts/config/contract-verification.js
> + *  2. Run the appropriate npm script in package.json to verify contract for a given network and environment
~~contract~~  contracts

2022-11-10 17:14 UTC, cliffhall commented on scripts/util/verify-suite.js
> + *  1a. If you want to verify all contract, leave contractList empty
~~contract~~  contracts

2022-11-10 17:14 UTC, cliffhall commented on scripts/util/verify-suite.js
> + *  1b. If you want to verify only a subset of contract, specify them in contractList.
~~contract~~  contracts

2022-11-10 17:14 UTC, cliffhall commented on scripts/util/verify-suite.js
> + *  2. Run the appropriate npm script in package.json to verify contract for a given network and environment
~~contract~~  contracts

2022-11-11 08:05 UTC, zajck commented on scripts/util/verify-suite.js
> + *  1.  Edit scripts/config/contract-verification.js. Addresses will be pulled from /addresses/<chainId>-<network>.json or environments file
fixed

2022-11-11 08:05 UTC, zajck commented on scripts/util/verify-suite.js
> + *  1a. If you want to verify all contract, leave contractList empty
fixed

2022-11-11 08:05 UTC, zajck commented on scripts/util/verify-suite.js
> + *  1b. If you want to verify only a subset of contract, specify them in contractList.
fixed

2022-11-11 08:05 UTC, zajck commented on scripts/util/verify-suite.js
> + *  2. Run the appropriate npm script in package.json to verify contract for a given network and environment
fixed

2022-11-11 08:05 UTC, zajck commented on scripts/util/verify-suite.js
> +const hre = require("hardhat");
Makes sense to move it to the top level, since it's role is closer to those scripts than utils.

Moved.

2022-11-11 09:26 UTC, hswopeams approved these changes

2022-11-11 16:47 UTC, anajuliabit approved these changes

2022-11-11 16:48 UTC, merged