This should quieten a couple of warnings
bosonprotocol/boson-protocol-contracts pull request #620
Opened 2023-04-26 14:04 UTC by mischat

This should address this issue https://github.com/bosonprotocol/boson-protocol-contracts/issues/619

2023-04-26 14:30 UTC, zajck requested changes

2023-04-26 14:30 UTC, zajck commented on contracts/protocol/facets/ExchangeHandlerFacet.sol
> +    uint256 private immutable EXCHANGE_ID_2_2_0; // solhint-disable-next-line
```suggestion
    uint256 private immutable EXCHANGE_ID_2_2_0; // solhint-disable-line
```

2023-05-10 12:32 UTC, anajuliabit approved these changes

2023-05-10 12:32 UTC, anajuliabit approved these changes

2023-05-10 12:32 UTC, anajuliabit submitted a review, later dismissed

2023-05-29 12:25 UTC, mischat commented on contracts/protocol/facets/ExchangeHandlerFacet.sol
> +    uint256 private immutable EXCHANGE_ID_2_2_0; // solhint-disable-next-line
This should be fixed.

2023-05-29 13:02 UTC, mischat commented
indeed, i will look at it, and make sure it is OK before pushing it up again... @zajck

2023-05-29 13:22 UTC, mischat commented
finally, this should work i guess ... Let's wait for the tests etc

2023-05-29 13:51 UTC, zajck approved these changes

2023-05-29 17:16 UTC, anajuliabit approved these changes

2023-05-29 17:16 UTC, merged