Deprecate clerk
bosonprotocol/boson-protocol-contracts pull request #638
Opened 2023-05-16 15:09 UTC by zajck

Closes #629

2023-05-18 11:48 UTC, anajuliabit requested changes
Could you also please update docs/task.md?

2023-05-18 11:48 UTC, anajuliabit commented on test/example/ZoraWrapperTest.js
I suppose this file shouldn't belong to this PR

2023-05-26 22:41 UTC, anajuliabit approved these changes

2023-06-02 11:24 UTC, mischat approved these changes
this LGTM ... i have suggested a minor copy change, otherwise, it makes sense, and nice to see no mention of the clerk in the contract, par the deprecated storage slots!

2023-06-02 11:24 UTC, mischat commented on contracts/protocol/facets/OrchestrationHandlerFacet1.sol
> +     * - Caller is not the supplied assistant and
```suggestion
     * - Caller is not the supplied assistant
```

2023-06-02 11:25 UTC, mischat requested changes
It looks like one of the unit tests isn't passing right now.

2023-06-02 11:26 UTC, mischat commented
@zajck it looks like we have unit tests failing, after merging in main

2023-06-02 12:23 UTC, zajck commented on contracts/protocol/facets/OrchestrationHandlerFacet1.sol
> +     * - Caller is not the supplied assistant and
Removed.

2023-06-02 13:05 UTC, mischat approved these changes
LGTM

2023-06-02 13:56 UTC, mischat commented
@anajuliabit ^^ you need to re-review, sorry

2023-06-06 23:43 UTC, anajuliabit approved these changes

2023-06-06 23:43 UTC, merged