Add minimal resolution period
bosonprotocol/boson-protocol-contracts pull request #673
Opened 2023-06-08 08:04 UTC by zajck

Fix #671

2023-06-09 13:05 UTC, anajuliabit requested changes
Looks good to me

Just a missing natspec

2023-06-09 15:19 UTC, zajck commented on contracts/protocol/bases/OfferBase.sol
> +                    _offerDurations.resolutionPeriod <= limits.maxResolutionPeriod,
Fixed here and on every other occasion.

2023-06-12 10:26 UTC, anajuliabit submitted a review, later dismissed

2023-07-04 21:47 UTC, mischat approved these changes
These look good to me. Thanks

2023-07-04 21:55 UTC, mischat commented
i have made a note that we will have to update the fair exchange policy to reflect this new minimum period. And I have reached out to the legal / compliance team to see if we need to reflect this change in our Buyer / Seller agreement.

2023-07-05 13:07 UTC, merged