More flexible getAvailableFunds
bosonprotocol/boson-protocol-contracts pull request #698
Opened 2023-06-22 12:30 UTC by zajck

Fixes #546 

And also alleviates the consequences of #322 and #679

2023-07-06 21:57 UTC, mischat commented
and more merge conflicts here @zajck

2023-07-07 12:56 UTC, mischat commented
fwiw, I would have totally just removed the "name" field, and make that the client's problem, but i like the solution here nonetheless...

2023-07-07 14:57 UTC, anajuliabit requested changes
Looks good, just some minor suggestions

2023-07-07 14:57 UTC, anajuliabit commented on contracts/interfaces/handlers/IBosonFundsHandler.sol
> +     * @param _entityId - id of entity for which availability of funds should be checked
add _limit and _offset parameters here

2023-07-07 14:57 UTC, anajuliabit commented on contracts/protocol/facets/FundsHandlerFacet.sol
> +     * @param _entityId - id of entity for which availability of funds should be checked
add _limit and _offset parameters here

2023-07-07 14:57 UTC, anajuliabit commented on contracts/protocol/facets/FundsHandlerFacet.sol
> +        return availableFunds;
no need for this return exist

2023-07-07 15:08 UTC, anajuliabit approved these changes

2023-07-07 15:27 UTC, mischat approved these changes

2023-07-07 15:47 UTC, merged