Remediate [BVR-06M] Insufficient Protection of Contract Assets
bosonprotocol/boson-protocol-contracts pull request #753
Opened 2023-08-04 08:05 UTC by zajck

Fix #743

2023-08-17 12:57 UTC, albertfolch-redeemeum commented on contracts/protocol/clients/voucher/BosonVoucher.sol
> +     * - _to is a contract that represents some assets (all contracts that imeplement `balanceOf` method, including ERC20 and ERC721)
```suggestion
     * - _to is a contract that represents some assets (all contracts that implement `balanceOf` method, including ERC20 and ERC721)
```

2023-08-17 12:57 UTC, albertfolch-redeemeum commented on contracts/interfaces/clients/IBosonVoucher.sol
> +     * - _to is a contract that represents some assets (all contracts that imeplement `balanceOf` method, including ERC20 and ERC721)
```suggestion
     * - _to is a contract that represents some assets (all contracts that implement `balanceOf` method, including ERC20 and ERC721)
```

2023-08-17 12:58 UTC, albertfolch-redeemeum commented on test/protocol/clients/BosonVoucherTest.js
> +        // const erc20 = await getContractFactory("Foreign20");
remove 
```suggestion
```

2023-08-18 10:56 UTC, levalleux-ludo requested changes
2 small suggestions

2023-08-18 10:56 UTC, levalleux-ludo commented on contracts/protocol/clients/voucher/BosonVoucher.sol
> +        uint256 balance;
Useless variable `balance`
```suggestion
```

2023-08-18 10:56 UTC, levalleux-ludo commented on contracts/protocol/clients/voucher/BosonVoucher.sol
> +        try IERC20(_to).balanceOf(address(this)) returns (uint256 _balance) {
Useless variable `_balance`
```suggestion
        try IERC20(_to).balanceOf(address(this)) returns (uint256) {
```

2023-08-22 15:06 UTC, levalleux-ludo approved these changes
LGTM

2023-08-22 15:22 UTC, albertfolch-redeemeum approved these changes

2023-08-22 17:06 UTC, merged