adding audit of v2.3
bosonprotocol/boson-protocol-contracts pull request #940
Opened 2024-04-09 11:11 UTC by thecryptofruit

this is from September 2023

2024-04-09 11:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bosonprotocol/boson-protocol-contracts?pullRequest=940) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bosonprotocol/boson-protocol-contracts?pullRequest=940) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bosonprotocol/boson-protocol-contracts?pullRequest=940) it.</sub>

2024-04-10 05:14 UTC, zajck requested changes
Please, update [docs/audits.md](https://github.com/bosonprotocol/boson-protocol-contracts/blob/cafc78a43dae615330af74ee420a9bbd82019c10/docs/audits.md) too

2024-04-11 06:52 UTC, zajck requested changes

2024-04-11 06:52 UTC, zajck commented on docs/audits.md
> +* [View Report - v2.3](audits/Omniscia_Audit_Report_Boson_Protocol_V2.3.pdf)
```suggestion
* [View Report - v2.3](audits/Omniscia_Audit_Report_Boson_Protocol_v2.3.pdf)
```

2024-04-11 06:52 UTC, zajck commented on docs/audits.md
> +* [View Report - v2.3](audits/Omniscia_Audit_Report_Boson_Protocol_V2.3.pdf)
Alternatively, the pdf file can be renamed to use capital V, the same as the previous two audits.

2024-04-11 14:56 UTC, zajck submitted a review, later dismissed

2024-04-18 08:37 UTC, zajck approved these changes

2024-04-18 13:40 UTC, levalleux-ludo approved these changes

2024-04-18 13:41 UTC, merged